name       : dhcpcd
version    : 8.0.2
release    : 9
source     :
    - https://roy.marples.name/downloads/dhcpcd/dhcpcd-8.0.2.tar.xz : 33a26ad561546cd2cfe1e6de6352a85df72b41c37def8c7eb00e90e57c627a5c
homepage   : https://roy.marples.name/projects/dhcpcd
license    : BSD-2-Clause
component  : network.base
summary    : dhcpcd - a DHCP client
description: |
    dhcpcd, a DHCP and DHCPv6 client. It's also an IPv4LL (aka ZeroConf) client. In layman's terms, dhcpcd runs on your machine and silently configures your computer to work on the attached networks without trouble and mostly without configuration.
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-enforce-a-hostname-change.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -m 0644 -D $pkgfiles/dhcpcd.service $installdir%libdir%/systemd/system/dhcpcd.service
    rm -frv $installdir/var


