name       : dhcpcd
version    : 8.1.6
release    : 11
source     :
    - https://roy.marples.name/downloads/dhcpcd/dhcpcd-8.1.6.tar.xz : 6c2934a3e1e67a5cfd5bb15b1efa71f65c00314ac1ccb5c50da8eae3a0b8147f
homepage   : https://roy.marples.name/projects/dhcpcd
license    : BSD-2-Clause
component  : network.base
summary    : dhcpcd - a DHCP client
description: |
    dhcpcd, a DHCP and DHCPv6 client. It's also an IPv4LL (aka ZeroConf) client. In layman's terms, dhcpcd runs on your machine and silently configures your computer to work on the attached networks without trouble and mostly without configuration.
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-enforce-a-hostname-change.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/dhcpcd.service $installdir%libdir%/systemd/system/dhcpcd.service
    rm -frv $installdir/var
